version: '3.8'
services:
  # 信令服务
  signal_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: signal_container
    network_mode: host
    working_dir: /service
    volumes:
      - ./certs:certs:ro
      - ./logs:logs:rw
      - ./sh/run:sh/run:ro
      - ./env.fat_main.yaml:env.fat_main.yaml:rw
    environment:
      NODE_ENV: prod
      SLAVE_FOR: master
    privileged: true
    restart: always
    command: ["/bin/bash", "-c", "pnpm run fat:main"]
  # 生产服务
  producer_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer_container
    network_mode: host
    working_dir: /service
    volumes:
      - ./certs:certs:ro
      - ./logs:logs:rw
      - ./sh/run:sh/run:ro
      - ./env.fat_producer.yaml:env.fat_producer.yaml:rw
    environment:
      NODE_ENV: prod
      SLAVE_FOR: producer
    privileged: true
    restart: always
    command: ["/bin/bash", "-c", "pnpm run fat:producer"]
  # 消费服务
  consumer_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer_container
    network_mode: host
    working_dir: /service
    volumes:
      - ./certs:certs:ro
      - ./logs:logs:rw
      - ./sh/run:sh/run:ro
      - ./env.fat_consumer.yaml:env.fat_consumer.yaml:rw
    environment:
      NODE_ENV: prod
      SLAVE_FOR: consumer
    privileged: true
    restart: always
    command: ["/bin/bash", "-c", "pnpm run fat:consumer"]